railsgirls/config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  resources :categories do
    resources :ideas, shallow: true
  end

  root :to => 'categories#index'

end

railsgirls/app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  
  has_many :idea
end

railsgirls/app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :category_id, presence: true

  mount_uploader :picture, PictureUploader
  
  belongs_to :category
end

railsgirls/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_categories

  def set_categories
    @categories_dd = Category.order("name ASC")
  end
end

railsgirls/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @empty_categories = Category.where('id NOT IN (?)', Idea.select("category_id"))
    @ideas = Idea.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    redirect_to root_path, notice: params[:notice]
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

railsgirls/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @category = Category.find(params[:category_id])
    @ideas = Idea.where("category_id = ?", params[:category_id])
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @category = Category.find(params[:category_id])
    @idea = @category.idea.build
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :category_id)
    end
end

railsgirls/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

railsgirls/app/helpers/application_helper.rb
module ApplicationHelper
end

railsgirls/app/helpers/categories_helper.rb
module CategoriesHelper
end

railsgirls/app/helpers/ideas_helper.rb
module IdeasHelper
end

railsgirls/app/helpers/pages_helper.rb
module PagesHelper
end

railsgirls/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsgirls/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', root_path %>

railsgirls/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<% @ideas.group_by(&:category).each do |category, ideas| %>

  <div class="category">
    <table class="table-hover sortable">
        <%= render partial: "shared/category_header", locals: {category: category, empty: false} %>
        <%= render partial: 'shared/ideas_tbody', locals: {ideas: ideas} %>
      </table>
      <hr>
  </div>

<% end %>

<% @empty_categories.each do |category| %>

  <table class="table-hover">
    <%= render partial: "shared/category_header", locals: {category: category, empty: true} %>
    <%= render partial: 'shared/ideas_tbody', locals: {ideas: []} %>
  </table>
  <hr>

<% end %>

<br>

<%= link_to 'New Category', new_category_path %>

railsgirls/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

railsgirls/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', root_path %>

railsgirls/app/views/ideas/_form.html.erb
<%= form_for form_params do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.map{ |c| [ c.name, c.id ] } %>
  <!-- <%= f.select :category_id, options_for_select(Category.all.map{ |c| [ c.name, c.id ] }, params[:category_id]) %>
-->  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>

  </div>
<% end %>

railsgirls/app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render partial: 'form', locals: {form_params: [@idea]} %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', root_path %>

railsgirls/app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="category">
  <table class="table-hover sortable">
    <%= render partial: "shared/category_header", locals: {category: @category, empty: @ideas.empty?} %>
    <%= render partial: 'shared/ideas_tbody', locals: {ideas: @ideas} %>
  </table>
  <hr>
</div>

<br>

<%= link_to 'Back', root_path %>

railsgirls/app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render partial: 'form', locals: {form_params: [@category, @idea]} %>

<%= link_to 'Back', root_path %>

railsgirls/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th class="th_vert">Name:</th>
    <td><%= @idea.name %></td>
  </tr>

  <tr>
    <th class="th_vert">Category:</th>
    <td><%= @idea.category.name %></td>
  </tr>

  <tr>
    <th class="th_vert">Description:</th>
    <td><%= @idea.description %></td>
  </tr>

  <% if @idea.picture? %>
    <tr>
      <th colspan="2">Picture:</th>
    </tr>
    <tr>
      <td colspan="2"><%= image_tag(@idea.picture_url, :width => 600) %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', root_path %>

railsgirls/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Idea App</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Start', root_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories_dd.each do |c| %>
              <li><%= link_to c.name, category_ideas_path(c) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Add new category', new_category_path %></li>
          </ul>
        </li>

        <li class="<%= 'active' if current_page?(pages_info_path) %>"><a href="/pages/info">About the Author</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container footer">
    &copy; Vera Clemens 2016
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

railsgirls/app/views/pages/info.html.erb
<h1>About the Author</h1>
<hr>
<p>Created by Vera Clemens based on the <a href="http://guides.railsgirls.com/app">Rails Girls App Tutorial</a></p>
<p><%= link_to 'mailto:vclemens@uni-potsdam.de' do %><span class="glyphicon glyphicon-envelope"></span> Send an email<% end %></p>
<p><%= link_to 'http://github.com/veracl' do %><span class="glyphicon glyphicon-globe"></span> Find me on github<% end %></p>

railsgirls/app/views/shared/_category_header.html.erb
<thead>
  <tr>
    <th class="cat" colspan="<%= empty ? '1' : '5' %>" data-defaultsort='disabled'>
      <%= link_to category.name, category_ideas_path(category) %>
    </th>
    <th class="cat button-s right" data-defaultsort='disabled'>
      <%= link_to new_category_idea_path(category) do %><span class="glyphicon glyphicon-plus"></span><% end %>
      <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove"></span><% end %>
    </th>
  </tr>
  <% if !empty %>
  <tr>
    <th style="width: 50px;" data-defaultsort='disabled'></th>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3" data-defaultsort='disabled'></th>
  </tr>
  <% end %>
</thead>

railsgirls/app/views/shared/_ideas_tbody.html.erb
<% unless ideas.empty? %>

      <tbody>
        <% ideas.each do |idea| %>
          <tr>
            <td style="width: 50px;">
              <% if idea.picture? %>
                 <%= image_tag idea.picture.thumb, :class => "thumb" %>
              <% else %>
                 <%= image_tag "no_picture.png", :class => "thumb" %>
              <% end %>
            </td>
            <td style="width: 15%"><%= idea.name %></td>
            <td style="width: 65%"><% if idea.description? %><%= idea.description.truncate_words(15) %><% else %><%= "No description available" %><% end %></td>
            <td class="button"><%= link_to idea do %><span class="glyphicon glyphicon-eye-open"></span><% end %></td>
            <td class="button"><%= link_to edit_idea_path(idea) do %><span class="glyphicon glyphicon-pencil"></span><% end %></td>
            <td class="button"><%= link_to idea, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove-circle"></span><% end %></td>
          </tr>
        <% end %>
      </tbody>

    <% else %>

      <tbody>
        <tr>
          <td style="height: 50px;" colspan="2">No ideas in this category.</td>
        </tr>
      </tbody>

<% end %>